//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int Id_ag { get; set; }
        public string Nom_ag { get; set; }
        public string Prenom_ag { get; set; }
        public string Phone_ag { get; set; }
        public System.DateTime DateNaissance_ag { get; set; }
        public string Adresse_ag { get; set; }
        public string Password_ag { get; set; }
        public byte[] Image_ag { get; set; }
    }
}
