//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Ordonnance_Medicament = new HashSet<Ordonnance_Medicament>();
            this.RendezVous = new HashSet<RendezVous>();
            this.Test = new HashSet<Test>();
        }

        public Doctor(int id_Doc, string nom_Doc, string prenom_Doc, DateTime? dateNaissance_Doc, string doc_specialite, int? doc_experience, int? doc_phone, string doc_addr, string doc_pass, byte[] doc_Image)
        {
            Id_Doc = id_Doc;
            Nom_Doc = nom_Doc;
            Prenom_Doc = prenom_Doc;
            DateNaissance_Doc = dateNaissance_Doc;
            Doc_specialite = doc_specialite;
            Doc_experience = doc_experience;
            Doc_phone = doc_phone;
            Doc_addr = doc_addr;
            Doc_pass = doc_pass;
            Doc_Image = doc_Image;
        }
        public int Id_Doc { get; set; }
        public string Nom_Doc { get; set; }
        public string Prenom_Doc { get; set; }
        public Nullable<System.DateTime> DateNaissance_Doc { get; set; }
        public string Doc_specialite { get; set; }
        public Nullable<int> Doc_experience { get; set; }
        public Nullable<int> Doc_phone { get; set; }
        public string Doc_addr { get; set; }
        public string Doc_pass { get; set; }
        public byte[] Doc_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordonnance_Medicament> Ordonnance_Medicament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendezVous> RendezVous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Test { get; set; }
    }
}
