//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordonnance_Medicament
    {
        private int qte;
        private int nbrjour;
        private string medicament;
        private int maladie;
        private int doctor;

        public Ordonnance_Medicament() { }

        public Ordonnance_Medicament(int qte, int nbrjour, string medicament, int maladie, int doctor)
        {
            this.qte = qte;
            this.nbrjour = nbrjour;
            this.medicament = medicament;
            this.maladie = maladie;
            this.doctor = doctor;
        }

        public Ordonnance_Medicament(int id_ord_med, int? quantite, int? nbrJr, string nom_medic, int? ord_Num, int? id_Doc)
        {
            this.id_ord_med = id_ord_med;
            Quantite = quantite;
            NbrJr = nbrJr;
            Nom_medic = nom_medic;
            Ord_Num = ord_Num;
            Id_Doc = id_Doc;
        }
        public int id_ord_med { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<int> NbrJr { get; set; }
        public string Nom_medic { get; set; }
        public Nullable<int> Ord_Num { get; set; }
        public Nullable<int> Id_Doc { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Ordonnance Ordonnance { get; set; }
    }
}
