//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        private int v;
        private string nom;
        private int prix;
        private int doctor;

        public Test() { }

        public Test(int v, string nom, int prix, int doctor)
        {
            this.v = v;
            this.nom = nom;
            this.prix = prix;
            this.doctor = doctor;
        }

        public Test(int test_num, string nom_test, int? prix_test, int? id_Doc, Doctor doctor)
        {
            Test_num = test_num;
            Nom_test = nom_test;
            Prix_test = prix_test;
            Id_Doc = id_Doc;
            Doctor = doctor;
        }
        public int Test_num { get; set; }
        public string Nom_test { get; set; }
        public Nullable<int> Prix_test { get; set; }
        public Nullable<int> Id_Doc { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
